sudo: required
language: perl
services:
- docker
install:
- echo "Skip install"
script:
- echo "Skip test"
after_success:
- docker --version
notifications:
  irc:
    channels:
      - irc.silex.kr#silex
      - irc.silex.kr:6667#silex
      - irc://irc.silex.kr#silex
      - irc://irc.silex.kr:6667#silex
      - ircs://irc.silex.kr#silex
      - ircs://irc.silex.kr:6667#silex
    password:
      secure: r2qUOcdazirINCXvtgpAK4DRcz8DaZRDSv9FxpTdhmCkgwiRsNew5Q3Uamxe2bkvtBqEKsC3Xl+QRFCCb+SDlgaE0xl4fXAuNrV+DsfFhSvAk8SASurS8uy3dIAqDVVxOXfMu39y8OOZkCnf3yIOF7tUYh8shDK5klA7Oh3ZSMBpz9uiWQBRJtGQb/KgHwPYzAahsMND2FhsKz1f7w3qiunXLMDydhkA2nvHBOcUVxQor98J+oksWSF0t3S+90aCyiGs4cGxcWV1ewiA03ZWUUu9otUKX5QtAwxPYgu7+O/G6O2JPuAjFiAeeneCLfJjEXEa1mhibVm2UlSGenW2QyEPvOgmOZd6xgO3+LsnG9F7e9c5w8VgLIzalYWfx4hRP+kdHyGCjG3Y/Ted9zGwMz5P0HWBoEeM0N6s+b4+wDDT9SlTP3FEvoQ9uO94ZKQ5O2nPOnSwiTlQWlRhiMNU01oXZxRsiXZ4kRUeif+azhmQv9EeA+2Vx31hCgwg/1EpgJVE3pZ5gPbIW93/Z0P469ENOVsPH3PCO/3pBu4cyykeJzRNdHEeiv/iY2EoHNzTsAHQc3kArYbgYZoQ/plwsnU6dzgH7fKszJX4LLCRtOVyIdXMx7k0R5dyA++H16h8flJAZko0Bazed/Z0JdGBiYENV0vNrtqxqIrmrC4FSSg=
