sudo: required
language: perl
services:
  - docker
# skipping installation step
install: true
script:
  - echo "Branch($TRAVIS_BRANCH), Tag($TRAVIS_TAG)"
after_success:
  - if [ "$TRAVIS_TAG" ]; then
    docker build -t aanoaa/fake-pause .;
    docker push registry.theopencloset.net/aanoaa/fake-pause;
    fi
notifications:
  email: false
