sudo: required
language: perl
services:
  - docker
install:
  - cpanm --notest --mirror http://www.cpan.org --mirror http://cpan.theopencloset.net --installdeps .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t aanoaa/fake-pause .
    docker push registry.theopencloset.net/aanoaa/fake-pause
    fi
script:
  - echo "0"
