sudo: required
language: perl
services:
  - docker
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t aanoaa/fake-pause .
    fi
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push registry.theopencloset.net/aanoaa/fake-pause
    fi
script:
  - echo "0"
