if: tag IS present
sudo: required
language: perl
services:
- docker
install:
- echo "Skip install"
script:
- echo "Skip test; aanoaa/fake-pause:$TRAVIS_TAG"
after_success:
- docker --version
- docker build -t "aanoaa/fake-pause:$TRAVIS_TAG" .
- docker tag "aanoaa/fake-pause:$TRAVIS_TAG" "registry.theopencloset.net/aanoaa/fake-pause:$TRAVIS_TAG"
- docker push "registry.theopencloset.net/aanoaa/fake-pause:$TRAVIS_TAG"
notifications:
  irc:
    matrix:
    - irc.silex.kr#silex
    password:
      secure: ix+zzgdMZ7T/pfm1ojLtZrbmcHDSzDJISNzPyjLmDTTWATuBRv/hXiNZaBjeW9O1pV8CjrDH2Z+lqdOU++dr0ZUNJpA6Vw1hqgqbKi+W1ga+89xA9YrUMzZ6VF15fQHj9FkzfLc/wShbFKiWjP0qdEEkWhwoJ6588QxIzj3HntYB7ew1bxK8NiJ06h/EItH+Hu1It2GDh21WgIggZGReTgre0srdtkIuDmfzJQWrM86ZdQl4vkKg0ovM13tVHRpXYucL2sey0MsHo6F4c+ZlDx4rXYY/1jU7M+R6ANAQ6JdQx7LhVw66efzghA+eiTmnUFOPnTRFCfXaCaUaVTX9Uo/7Cz7ocROKMdUdeNqKTr/RUM31oQ6hQe04MpN/6bzFjARMwMh4osUAv6XD2e8TZVkf5truP1W2+4INlHNXoSc4pEmzGh0BsDnSPgdrK6+pGOoRq4k27xwOCqdpR9wEpQ96+Xxrt1rHw37LQV4vBA5EOS3isCRk7h5F36tJIWr3f7+l1GrknP0S6lTSG8kppHKW2ctKIKU7sr6pVKR/XV92jGiB0CGP+MQOjNwjlGuytuy3e2s1tjLqCkrhdrwpJGJsdVLy/Nhi0WdFZ6wHt4Dn10ABo7yNaiJ3xgmtgVie8CVgdM6mBbZHXyq1HITiP6NdkdPGwlfvHYpnUkGbRV0=
  email: false
